name: KawaiiTweetGenerator
description: かわいいツイート文面生成器
version: 0.9.0
homepage: https://developerspackages-org.github.io/KawaiiTweetGenerator/

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  build_runner: '>=1.6.2 <2.0.0'
  build_web_compilers: '>=2.12.0 <3.0.0'


