name: KawaiiTweetGenerator
description: かわいいツイート文面生成器
version: 0.9.0
homepage: https://developerspackages-org.github.io/KawaiiTweetGenerator/

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:



